### ISSUE TITLE
Duplication of Error Messages

### ISSUE THREAD

**Issue by AnnaAaBrekke** [AnnaAaBrekke/BidVault#17]
The same error message appears two times, causing user confusion and a poor user experience.

**Steps to Reproduce:**
1. Perform action X (e.g., submit a form or make a request).
2. Trigger error condition Y (e.g., invalid input, server failure).
3. Notice that the same error message appears two times on the screen.

**Expected Behavior**: Error messages should only appear once for each unique error, regardless of the number of components or systems that trigger them. The error should be clearly visible but not duplicated.

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified the FormHandler class to prevent duplicate error messages from appearing. Added a new method to check if an error message is already displayed and updated the error handling logic accordingly.

You can review changes in this commit: https://github.com/mnmnk43434/AnnaAaBrekke-BidVault-17/commit/44df8bd5f639d96b52798239168591be916939c8.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by AnnaAaBrekke** [comment]
A utility function now ensures that error messages are displayed only once, even if triggered by multiple components or actions. This fix improves the overall user experience by eliminating redundant error messages and ensuring that errors are clearly communicated.
